import { StyleSheet } from "react-native";

export const buttonStyles = StyleSheet.create({
  button: {
    backgroundColor: "#F8F8F8",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#DDDDDD",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  buttonText: {
    color: "#333333",
    fontSize: 16,
    fontWeight: "600",
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  blueButton: {
    backgroundColor: "#007BFF",
    borderWidth: 0,
  },
  blueButtonText: {
    color: "#FFFFFF",
  },
  redButton: {
    backgroundColor: "#DC143C",
    borderWidth: 0,
  },
  redButtonText: {
    color: "#FFFFFF",
  },
  dropdownButton: {
    backgroundColor: "#EFEFEF",
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownButtonText: {
    fontSize: 16,
    color: "#333333",
    fontWeight: "600",
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
});